project:
  type: website
  output-dir: docs

website:
  page-footer: 
    center: "Copyright 2025, Tipsarp Kittisiam" 
  search: false
  back-to-top-navigation: true
  navbar:
      left:
        - href: index.qmd
          text: About Me
        - text: "Veterinarian Well-being Research"
          href: vet_mh/vet_mh.qmd

format:
  html:
    theme: pulse
    css: styles.css

editor: visual
