project:
  type: website
  output-dir: docs

website:
  page-footer: 
    center: "Copyright 2024, Tipsarp Kittisiam" 
    right: 
      - icon: github
        href: https://github.com/
  search: false
  back-to-top-navigation: true
  navbar:
      left:
        - href: index.qmd
          text: About
        - href: cv.qmd
          text: CV
        - text: "Research"
          menu: 
            - href: vet_mh.qmd
              text: Veterinarian Mental Health
      right: 
        - icon: linkedin
          href: https://www.linkedin.com/in/tipsarpk/
        - icon: envelope
          href: mailto:tkittisi@uoguelph.ca
        

format:
  html:
    theme: pulse
    css: styles.css

editor: visual
